<?php

return [
    'GET' => [
        '/' => 'DashboardController@index',
        '/login' => 'AuthController@showLogin',
        '/logout' => 'AuthController@logout',
        
        '/reports/sales' => 'SalesReportController@index',
        '/reports/sales/data' => 'SalesReportController@data',
        '/reports/sales/export' => 'SalesReportController@export',
        
        '/reports/top-items' => 'TopItemsController@index',
        '/reports/top-items/data' => 'TopItemsController@data',
        '/reports/top-items/export' => 'TopItemsController@export',
        
        '/reports/category-sales' => 'CategorySalesController@index',
        '/reports/category-sales/data' => 'CategorySalesController@data',
        
        '/reports/feedback' => 'FeedbackController@index',
        '/reports/feedback/data' => 'FeedbackController@data',
        
        '/reports/waiter' => 'WaiterPerformanceController@index',
        '/reports/waiter/data' => 'WaiterPerformanceController@data',
        
        '/reports/gst' => 'GstReportController@index',
        '/reports/gst/data' => 'GstReportController@data',
        '/reports/gst/export' => 'GstReportController@export',

        '/qr-codes' => 'QrCodeController@index',
        
        '/settings' => 'SettingsController@index',

        '/api/home' => 'ApiController@home',
        '/api/orders' => 'ApiController@orders',
        '/api/order-detail' => 'ApiController@orderDetail',
        '/api/menu-items' => 'ApiController@menuItems',
        '/api/menu-item-detail' => 'ApiController@menuItemDetail',
        '/api/tables' => 'ApiController@tables',
        '/api/table-room-detail' => 'ApiController@tableRoomDetail',
    ],
    'POST' => [
        '/login' => 'AuthController@login',
        '/api/register' => 'ApiController@register',
        '/api/login' => 'ApiController@login',
        '/api/create-order' => 'ApiController@createOrder',
        '/api/update-order-status' => 'ApiController@updateOrderStatus',
        '/api/add-order-items' => 'ApiController@addOrderItems',
        '/api/update-order-item-status' => 'ApiController@updateOrderItemStatus',
        '/api/menu-categories' => 'ApiController@menuCategories',
        '/api/create-menu-item' => 'ApiController@createMenuItem',
        '/api/update-menu-item' => 'ApiController@updateMenuItem',
        '/api/update-menu-item-availability' => 'ApiController@updateMenuItemAvailability',
        '/api/delete-menu-item' => 'ApiController@deleteMenuItem',
        '/api/tables' => 'ApiController@tables',
        '/api/table-rooms' => 'ApiController@tableRooms',
        '/api/table-room-detail' => 'ApiController@tableRoomDetail',
        '/api/create-table-room' => 'ApiController@createTableRoom',
        '/api/update-table-room' => 'ApiController@updateTableRoom',
        '/api/update-table-room-status' => 'ApiController@updateTableRoomStatus',
        '/api/delete-table-room' => 'ApiController@deleteTableRoom',
        '/api/update-qr-image' => 'ApiController@updateQrImage',
        '/api/app-users' => 'ApiController@appUsers',
        '/api/app-user-detail' => 'ApiController@appUserDetail',
        '/api/create-app-user' => 'ApiController@createAppUser',
        '/api/update-app-user' => 'ApiController@updateAppUser',
        '/api/update-app-user-status' => 'ApiController@updateAppUserStatus',
        '/api/delete-app-user' => 'ApiController@deleteAppUser',
        '/qr-codes/generate' => 'QrCodeController@generate',
        '/qr-codes/generate-missing' => 'QrCodeController@generateMissing',
        '/qr-codes/revoke' => 'QrCodeController@revoke',
        '/settings' => 'SettingsController@update',
    ],
    'OPTIONS' => [
        '/api/register' => 'ApiController@options',
        '/api/login' => 'ApiController@options',
        '/api/home' => 'ApiController@options',
        '/api/orders' => 'ApiController@options',
        '/api/order-detail' => 'ApiController@options',
        '/api/create-order' => 'ApiController@options',
        '/api/update-order-status' => 'ApiController@options',
        '/api/add-order-items' => 'ApiController@options',
        '/api/update-order-item-status' => 'ApiController@options',
        '/api/menu-categories' => 'ApiController@options',
        '/api/menu-items' => 'ApiController@options',
        '/api/menu-item-detail' => 'ApiController@options',
        '/api/create-menu-item' => 'ApiController@options',
        '/api/update-menu-item' => 'ApiController@options',
        '/api/update-menu-item-availability' => 'ApiController@options',
        '/api/delete-menu-item' => 'ApiController@options',
        '/api/tables' => 'ApiController@options',
        '/api/table-rooms' => 'ApiController@options',
        '/api/table-room-detail' => 'ApiController@options',
        '/api/create-table-room' => 'ApiController@options',
        '/api/update-table-room' => 'ApiController@options',
        '/api/update-table-room-status' => 'ApiController@options',
        '/api/delete-table-room' => 'ApiController@options',
        '/api/update-qr-image' => 'ApiController@options',
        '/api/app-users' => 'ApiController@options',
        '/api/app-user-detail' => 'ApiController@options',
        '/api/create-app-user' => 'ApiController@options',
        '/api/update-app-user' => 'ApiController@options',
        '/api/update-app-user-status' => 'ApiController@options',
        '/api/delete-app-user' => 'ApiController@options',
    ],
];
